### ISSUE TITLE
Can't get it to work properly with AngularJS

### ISSUE THREAD

**Issue by yoshuawuyts** [cferdinandi/smooth-scroll#2]
Do you have any idea if the script could fail if interacting with angular.js (or any other scenario?) I'm currently having a little trouble to get it going. Right now it just jumps to my `href='#idname'`.

I'd be most grateful if you could help me out, I'm really excited to get this running on my page!

**Comment by leolux** [comment]
Hi, I am running AngularJS 2 and I also had this issue. But I found a way to stop Angular from intercepting the anchor link. So instead of writing this:
    <a href="#idname" data-scroll>Goto</a>
When using Angular I write the following:
    <a onclick="return false;" href="#idname" data-scroll>Goto</a>

Now the smoothScroll is doing its work the same way as without AngularJS. But maybe there is a better solution than currently. I am not sure if the issue is caused by AngularJS alone or by its ng-route module. Maybe someone likes to figure out the root cause of this issue.
