### ISSUE TITLE
selector: '[href*=#]' not working

### ISSUE THREAD

**Issue by horgen** [cferdinandi/smooth-scroll#201]
I'm trying to make this script work on all elements with a href attribute that contains a hashtag. In the documentation it's says it must be a valid CSS selector. Is this not valid?

**Comment by cferdinandi** [comment]
You're missing the quotes around the `#`. Have you tried `selector: '[href*="#"]' `?

**Comment by horgen** [comment]
I have tried '[href*="#"]' and "[href*='#']" aswell. Still doesn't work :/

**Comment by cferdinandi** [comment]
I'll do some debugging and report back. Thanks.

**Comment by horgen** [comment]
Thanks! If it helps, this is how the URLs look like: /about-us/#compliance

**Comment by cferdinandi** [comment]
Aha! This is the issue: 

* https://github.com/cferdinandi/smooth-scroll/blob/master/dist/js/smooth-scroll.js#L411
* https://github.com/cferdinandi/smooth-scroll/blob/master/dist/js/smooth-scroll.js#L99-L169

In particular, `getClosest` is looking for a data attribute, class, ID, or element type rather than any valid CSS selector, so it's failing and return null. I would need to rewrite getClosest to support your use case (and I should). In particular, it looks like I should use the `matches` API: https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Browser_compatibility

I'll update this issue once it's been addressed, though I've got a few other commitments at the moment and cannot guarantee a completion date.

**Comment by cferdinandi** [comment]
@horgen I haven't had time to address this just yet, but as a workaround in the interim, you can leave the default selector in place and use `querySelectorAll` to apply the `data-scroll` attribute. This can happen at any time, since the script checks for the selector on click rather than in advance.

```js
var anchors = document.querySelectorAll( '[href*="#"]' );
for (var i = 0, len = anchors.length; i < len; i++) {
    anchors[i].setAttribute( 'data-scroll', 'true' );
}
smoothScroll.init();
```

**Comment by cferdinandi** [comment]
In looking at this more closely, the `match` method is not widely supported. Accordingly, I'm recommending one programatically add the `data-scroll` attribute as part of the `init` process:

```js
;(function (window, document, undefined) {

    'use strict';

    // Cut the mustard
    var supports = 'querySelector' in document && 'addEventListener' in window;
    if ( !supports ) return;

    // Get all anchors
    var anchors = document.querySelectorAll( '[href*="#"]' );

    // Add smooth scroll to all anchors
    for ( var i = 0, len = anchors.length; i < len; i++ ) {
        anchors[i].setAttribute( 'data-scroll', true );
    }

    // Initial smooth scroll (add your attributes as desired)
    smoothScroll.init();

})(window, document);
```
