### ISSUE TITLE
callback function in individual link

### ISSUE THREAD

**Issue by IvorHum** [cferdinandi/smooth-scroll#204]
I'm trying to use the callback function in an individual link as below but can't get it to work:
<a data-scroll
   data-options='{
                    "easing": "easeOutCubic",
                    "how do I use the callback:function quoted below"
                }'
>

callback: function () { window.location = '/ipam/?increment=first'; }

Could you give me a pointer for this please.

**Comment by cferdinandi** [comment]
Hi @IvorHum - So, to be candid, I'm not 100% sure you can, since the single quotes in the JS method effectively close the opening single quote for the data attribute. BUT, two things you might try:

1. Using hexcode for your JS function quotes: http://stackoverflow.com/questions/4015345/how-to-properly-escape-quotes-inside-html-attributes (ex. `&quot;`)
2. You may instead have to use the global callback set during `init`, but run a check to see if the desired anchor link is the one that was clicked. Example below.

```js
smoothScroll.init({
	callback: function ( toggle, anchor ) {

		// One option
		if ( anchor === '#someValue' ) {
			window.location = '/ipam/?increment=first';
		}

		// Another
		if ( toggle.hasAttribute( 'data-scroll-special' ) ) {
			window.location = '/ipam/?increment=first';
		}
		
	}
});
```

**Comment by IvorHum** [comment]
Many thanks, Chris.

I think you're probably right: I can’t get callback: function to work in an <a> link. But using the global callback with a set of checks on the anchor attribute is working a treat.

All best,

Ivor

=-=-=-=-=-=-=-=-=-=-=-=-=
Ivor Humphreys
19 Southlands
East Grinstead
West Sussex
RH19 4DB
t    01342 314943
m  07989 215986
w  goodimprint.co.uk <http://goodimprint.co.uk/>
=-=-=-=-=-=-=-=-=-=-=-=-=
