### ISSUE TITLE
[Feature request] Animating links to current *and* other pages

### ISSUE THREAD

**Issue by Flaburgan** [cferdinandi/smooth-scroll#212]
You explain in the readme that to animate link to other pages, we should remove `data-scroll` attribute and use `smoothScroll.animateScroll`. My problem is, my links (with `href="home.html#title1"` etc.) are in the header. So, if I'm on home.html, it should have `data-scroll`, if I'm on another page, it should be manually animated.

Could it be possible to improve smooth-scroll to let us put `data-scroll` on every anchor and when the link is clicked, to check if the anchor is on the current page or not?

I know I can solve my problem by checking the page and manually add `data-scroll` if I'm on the current page, but it would be cleaner if this becomes a core feature of smooth-scroll.

Thanks for your work!

**Comment by cferdinandi** [comment]
Hey there! So I absolutely agree that this would be much cleaner baked into the core. 

That said, I'm constantly trying to balance the desire for new features against wanting to keep the core as lightweight as possible. This particular use case feels like *just* enough of an edge case that I'd prefer to see it enabled via the API rather than baked in.

I may change my mind about this down the road, but for now, I'd prefer to keep this out of the core. Sorry!

**Comment by cferdinandi** [comment]
Well - I had a complete change of hear on this pretty quickly. This functionality is added with version 10: https://github.com/cferdinandi/smooth-scroll/pull/215

**Comment by Flaburgan** [comment]
Awesome! Thank you very much for your work. :cookie: 

The release page talks about v8 released 2 days ago when the code and you are mentioning the v10. Is that the same version?

**Comment by cferdinandi** [comment]
Yea, I fudged up the version tags when I first pushed it. It's v8—ignore my comment above.

**Comment by cferdinandi** [comment]
Ok, so the bad news... there were a ton of weird quirks with the rewrite, and this was one of them. It's damn near impossible to prevent the initial page jump when the page loads, so it was resulting in some really jerky animation issues.

As a result, no longer supported in v9. =(
