### ISSUE TITLE
Update URL? Says version 8.0

### ISSUE THREAD

**Issue by scottshefler** [cferdinandi/smooth-scroll#219]
Hi, what happened to the option to disable the anchor link from showing up in the address bar? Also, it says v 10 is the latest but when you download says v8.0.0

**Comment by cferdinandi** [comment]
New approach to how this script works: Instead of preventing default on click, script now temporarily removes id from the target element to prevent scroll jumping, then adds it back after the `hashchange`. This provides built in browser history and forward/backward button support. It also allows for animated scrolling on page load.

As a side effect of this switch, you can no longer disable URL updates, but that's not necessarily a bad thing. Is there a use case where it's necessary to not display the hash, or is it more an aesthetic thing?

Thanks for the catch about the v10/v8 mixup. Just corrected the tag.

**Comment by scottshefler** [comment]
I guess an aesthetic thing. Just seems nice to be able to disable it to seem more like a seamless scroll rather than treating it as an anchor link. Some use cases might be people refreshing the page and not wanting to animate scroll to that area or maybe they want to share that page and copy the link of the page but the anchor is in there. Still would be nice to have an option to prevent the url from updating. Even if that comes at the expense of the new features you mentioned.

**Comment by cferdinandi** [comment]
> refreshing the page and not wanting to animate scroll to that area

That actually is configurable. But the other stuff... Function over aesthetics.

**Comment by cferdinandi** [comment]
Good news for you, @scottshefler: there were just too many bugs/quirks with the code rewrite in v8, so I just pushed a v9 that brings back `updateURL` disabling.
