### ISSUE TITLE
Ban pressed again

### ISSUE THREAD

**Issue by senja006** [cferdinandi/smooth-scroll#229]
It is necessary to prohibit the re-pressing the button while scrolling occurs. Otherwise, there are pages twitching

**Comment by cferdinandi** [comment]
Good catch on this bug. Rather than preventing someone from clicking another link, I decided to terminate the current animation mid-scroll and start the new one if a scroll link is re-clicked (or another one is clicked instead).

I think this is better for the user as it doesn't prevent them from doing whatever it is they'd like to do.

Fixed with https://github.com/cferdinandi/smooth-scroll/pull/230.
