### ISSUE TITLE
Actually publish project to npm

### ISSUE THREAD

**Issue by wookiehangover** [cferdinandi/smooth-scroll#244]
Currently, the npm install for this package refers back to github rather than publishing directly to npm, unless I'm missing something.

**Comment by wookiehangover** [comment]
Hey thanks for closing without comment!

I went ahead and published this to npm under the name `smooth-scroll` yay open source!

**Comment by cferdinandi** [comment]
hey, thanks for not taking 30 seconds to look at previous issues: https://github.com/cferdinandi/smooth-scroll/issues?q=is%3Aissue+is%3Aclosed. I was actually preparing a comment, but if you want to be a jerk about it...

My reasons for not publishing this to NPM are well documented: https://github.com/cferdinandi/smooth-scroll/issues/241

Since I will not be pushing updates to NPM, you've either just taken on ownership of doing so or screwed people who use the NPM version of the script out of bug fixes and updates.

**Comment by cferdinandi** [comment]
BTW, if you're going to "yay open source" this, please fork and publish your forked version on NPM, not my script.

**Comment by cferdinandi** [comment]
Just to clarify: please remove this script from NPM, fork it, and republish it from your own account if that's something you're interested in.

**Comment by wookiehangover** [comment]
> please fork and publish your forked version on NPM, not my script.

According to the terms of your license (see below) I have the right to publish this to npm, and I think given the history of open issues in the past, that the community will benefit from it.

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, **publish, distribute**, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

**Comment by cferdinandi** [comment]
You may be within your rights, but it's a jerk move to do so. Fork it and publish it that way if you want. I don't care. But I don't want people to think its a sanctioned (and more importantly updated and supported) version of my script.

**Comment by cferdinandi** [comment]
Seriously dude, just remove the link back to this GitHub repo and I'll be happy. Also, the MIT license extends to the code, not the documentation, which I've worked hard to write and maintain.

**Comment by wookiehangover** [comment]
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and **associated documentation**

**Comment by cferdinandi** [comment]
This is pretty straightforward. I've made a deliberate choice not to host this on NPM. You're welcome to do so, but please change the link back to GitHub so that it does not point to this repo, as I will not be pushing updates or bug fixes, and do not want someone thinking it's the official, updated version.

**Comment by cferdinandi** [comment]
As you're probably already aware, I've also already escalated this through the NPM dispute resolution process.
