### ISSUE TITLE
Easing killed when the bottom of the page is reached

### ISSUE THREAD

**Issue by lucaorio** [cferdinandi/smooth-scroll#249]
**Amazing** script! :+1: 

The easing is killed when an element is too close to the bottom of the page. 
Is there a way to fix this behavior? Basically when the element `top` is bigger than `$(document).height() - $(window).height()`, force the ending of the scroll to `$(document).height() - $(window).height()`

(Please don't look at the crappy jQuery syntax haha)

**Comment by cferdinandi** [comment]
Sigh... this is a bug that has plagued me since the beginning, and I've never been able to figure out a way to properly fix it.

Certain easing patterns fizzled out when scrolling up from the bottom. In my experience, any of the `easeOut*`easing patterns will work, but some of the others fail. It's lame, but I would try setting a custom option for that particular link with a different easing pattern.

See this thread for more details: https://github.com/cferdinandi/smooth-scroll/issues/49

This is also a good reminder for me to update the "Known Issues" section of the readme. Thanks, and sorry for the lame solution to a very real bug.
