### ISSUE TITLE
Let animateScroll take an element rather than a selector

### ISSUE THREAD

**Issue by ComLock** [cferdinandi/smooth-scroll#260]
Lets say you want to scroll to an element, which does not have a unique id or name.

You could figure out some unique selector using:
https://github.com/ericclemmons/unique-selector (I was unable to use that module due to babelify issues)

But I think it would be much nicer if you could simply pass along the element to smoothScroll...

**Comment by cferdinandi** [comment]
Smooth Scroll deliberately uses IDs so that it can behave an an *enhancement* to browser-native anchor link behavior. It's a progressive enhancement. If the script fails or breaks, your links still work.

This would not be the case with what you're proposing. As such, I'm closing this out as `wontfix`.

**Comment by ComLock** [comment]
So I guess smoothScroll should be renamed to smoothScrollToAnchor then...

Cause I'm not talking about links, but dynamic content.

**Comment by cferdinandi** [comment]
> A lightweight script to animate scrolling to anchor links.

**Comment by cferdinandi** [comment]
Also it's poorly documented but animateScroll accepts a scrollTo position. If you can calculate that in your own you can animate to dynamic content with it: https://github.com/cferdinandi/smooth-scroll#animatescroll
