### ISSUE TITLE
Problem in IE: toggle.origin is undefined

### ISSUE THREAD

**Issue by serratus** [cferdinandi/smooth-scroll#273]
Thanks for this awesome library. It works pretty much in any browser, but I have a problem in IE (11):

The click-event is prematurely cancelled because `toggle.origin !== location.origin` evaluates to `true`. See [L445](https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L445) in your source code. It seems like IE does not support the `origin` property on the AnchorElement (see [W3Schools](http://www.w3schools.com/jsref/prop_anchor_origin.asp))

For my use-case I just removed the first expression of the `if` conditional because I don't need to check for origin.

Have you observed the same issue? I've just tried your [demo](http://cferdinandi.github.io/smooth-scroll/) in IE 11 and it just won't work. Thanks for your help.

**Comment by cferdinandi** [comment]
This appears to be a bug on older versions of IE11 on Windows 10 that [has since been patched](https://developer.mozilla.org/en-US/docs/Web/API/Window/location#Browser_compatibility).

I'm comfortable with this being a progressively enhanced feature for browsers that don't have the patch in place (since the anchor link will still work---it just won't smooth scroll).

That said... compatibility for `location.origin` is IE11 and up. This is a recent addition to Smooth Scroll, which boasts IE9+ browser support. I either need to update the documentation, or, ideally, [implement this lightweight polyfill](http://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/).

**Comment by serratus** [comment]
Thanks for the fast feedback. It's not that `window.location.origin` is `undefined` but the `origin` property of the AnchorElement.

This is the output of the console in IE 11:
![smooth-scroll-ie11-origin](https://cloud.githubusercontent.com/assets/1381822/18035059/c28099ee-6d4d-11e6-9f32-32d0cb69d8f8.PNG)

This shows that I'm using the patched version since `window.location.origin` is defined. Am I missing here something?

**Comment by cferdinandi** [comment]
Probably not. I decided to revert from `origin` to `hostname`: https://github.com/cferdinandi/smooth-scroll/pull/276

This gives greater backwards compatibility out of the box. I don't have a windows machine to test on right now. Can you confirm whether or not that is defined on an anchor link in Windows for me? Thanks!

**Comment by serratus** [comment]
Thanks, that seems to work just fine. I tested this in IE11 and Edge, and both browsers behave like they should :+1:

**Comment by cferdinandi** [comment]
Awesome! Thanks for letting me know about this!
