### ISSUE TITLE
Paint performance, all browsers.

### ISSUE THREAD

**Issue by inspiredlabs** [cferdinandi/smooth-scroll#286]
When the page scrolls moderate distances, paint performance can take quite a hit.

What should be done to mitigate this? I've noticed it's especially important when the DOM has 1000> elements?

**Comment by cferdinandi** [comment]
Do you have an example link I could take a look at? Is there something I should specifically be looking at to gauge bad paint performance?

**Comment by inspiredlabs** [comment]
http://inspiredlabs.co.uk/per.umbria.it/en/index.html

**Comment by inspiredlabs** [comment]
I've tested the site on many different devices and browsers. Mobile devices seem to struggle to display the animation at all when the site scrolls more than two screens. 

For example, scrolling on an iPad mini (2012), and iPhone5S (2013) is choppy, or when it's full screen launched from the homescreen it simply goes transparent. Scrolling on the MotoG 4G (2013) is flickery and pixelates on scrolling a several screens deep. All the devices are up to date and seem to animate the scroll if the distance is low.

I have avoided excessive CSS3 `box-shadow` and have tried to mimic the effect of the right hand menu floating by using `outline:1px grey solid`. This doesn't fix the paint issue.

**Comment by cferdinandi** [comment]
I see what you mean. I did some debugging with iOS, and it looks like Flickity is calling a ton of JS events throughout the scrolling---specifically, the `animate` method.

I suspect if you removed Flickity you would see a dramatic improvement in the animation performance. I believe this is hogging your memory, resulting in the jankiness. For example, [check out this page on my own site](https://gomakethings.com/ditching-jquery/), which, while not quite as long as yours, is a quite lengthy document. The animation is smooth all the way to the bottom.

Flickity should really debounce on scroll (ie. only run it's scroll event every 15ms or so instead of continuously). What it's doing right now (https://github.com/metafizzy/flickity/blob/master/dist/flickity.pkgd.js#L2730) is crippingly on a lengthy, animated scroll.
