### ISSUE TITLE
Calculating speed based on travel distance [feature request]

### ISSUE THREAD

**Issue by DrummerHead** [cferdinandi/smooth-scroll#300]
It would be interesting to have a new setting on initializing that replaces "speed" (which is the most appropriate name for what I'm suggesting :P) that determines not the duration of the animation but the actual speed of the animation.

What I'm getting at is that sometimes you scroll 100 pixels, and you get a, let's say, 500ms animation. The user perceives this animation as slow. Now let's say that in the same page you jump 6000 pixels down, and you have the same 500ms animation. Now it's warp speed time! And can get jarring.

Since I think that you're already calculating the distance between the place you are and the place you want to be, it would be interesting to calculate "speed" in a linear relationship to that distance, so that you just provide the multiplier to the script (the speed, but we should call it something else, like "pace" for backwards compatibility's sake).

Also, thanks for your work! It's a great solution. I would be using [scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) but only Firefox seems to support it at the time of writing (and you can't send any parameters). Cheers!

**Comment by cferdinandi** [comment]
Hey there, I actually think this is a great suggestion. Unfortunately, it's also one I frankly have no idea how to implement.

Given the broad use of this, I imagine a number of folks (myself included) like the consistent time-based scrolling. The really fast scrolling vs. really slow allows you to get folks to where they want to go quickly while still conveying a sense of distance. I wouldn't want that to go away for folks who want it.

But it would also require me to rewrite some code to do it, so to be honest... I don't see this getting implemented any time in the near to mid-future.

**Comment by stratboy** [comment]
I think your script is great.

I can show a jquery.animate - based example, extracted from some code of mine, of how to achieve the requested feature. Probably not the only way, and not necessarily the best, but it does the job. Anyway, this is just my personal take. You can take idea from here very easily and then maybe implement in your smooth-scroll.js.

``` js
  var maxtime = 6500;
  var d = Math.abs($(selector).offset().top - $(window).scrollTop());
  var ratio = d/$(document).height();
  var time = maxtime * ratio;
  // > then pass time to jquery.animate.
```

So, ideally, you could implement all of this and then add 2 options for the user: 

```
distance_based_speed: boolean
max_duration: number
```

**Comment by stratboy** [comment]
No :) The opposite. If you've got a huge page to scroll, divided in sections (use case: one-page website), you want faster scrolls for near sections (short distance) and slower scroll for far sections (long distance). It seems a paradox, I know. But did you ever try? Scrolling, say, a 6000px page full of things in just only 1 second, for example, it's quite offending for the eyes. Also, doesn't let the user to get a hint of what's passing under his eyes. It's sort of a violent thing.

Also, you can think of it from another point of view: what speed really is? it's space/time. So, keeping a  fixed time, in fact you're causing different speeds for different distances. Going from section 1 to section 2 will be slower than going from section 1 to section 10.

Instead, by varying the time based on distance, you're sort of keeping the speed much more consistent.
The user will have a more similar comfort for short distances as well as for long ones. The feeling will be much more the same, because he will be able to see/catch some of the sections details while scrolling, in both situations (short/long).

**Comment by cferdinandi** [comment]
Ah yea, that makes perfect sense. 

Thanks for providing such a detailed explanation and some sample code. I'm going to implement this feature, and you helped a lot!

For transparency, here's the plan:

- This will be a breaking change and major version bump.
- Animating this way will be the default that can be turned off (rather than the other way around).
- The `speed` option will roughly refer to *time to travel 1000px*, much like mph/kph in a car.
- If `variableTime` (or whatever the option gets called) is set to `false`, `speed` will instead be the absolute amount of time for the animation.
- There will also be variables to set minimum and maximum animation times.

Thanks again. Excited about this!

**Comment by cferdinandi** [comment]
Got this coded and tested. Just need to update the documentation and push. Thanks for making this happen!

**Comment by cferdinandi** [comment]
Alright, this is officially live with version 15! Just pushed updated docs. It may take a few minutes for the CDN cache to refresh, but this feature is now implemented *and* set as the default.

Thanks again for all of your help!

**Comment by stratboy** [comment]
My pleasure :)

**Comment by stratboy** [comment]
Just to advise: your codepen demo doesn't work.

Chris Ferdinandi ha scritto:

**Comment by stratboy** [comment]
Another suggestion, but this is probably a bit more difficult and offtopic here. Anyway, I'd like to point it out. It would be great if the script could be manually called, instead of auto-attached to a certain class of links. In other works, I think it would be even more versatile if it was based on target objects rather than links. This is for a certain number of reasons:

- You're attaching click events to buttons, but they often will already have the same events attached.

- You're attaching click events to single objects, while one could very often take advantage of delegation instead.

- You're assuming anchors here, but it's not always the case. Thus, you're forcing adding ids to any target object. One cannot add something differet from '#[name]' in anchors href, so if you expect the script to be attached to links, you're also forcing adding ids to target objects. But maybe one wants just smoot-scroll to a .something object (or any other selector) by clicking a button that's not a link.
not to say that link anchors have really much much more implications than simply scroll to an object. Not always desiderable.

- You're assuming that the behaviour of a button will always be the same. Instead, behaviour could change based on the application state (sometimes smooth scroll, an later just go straight to the target point, or maybe do nothing).

For all these reasons (and probably more), the script would be much more versatile it would just do what is meant to do: scroll. Not managing events, just scroll. So instead of `new SmoothScroll('a[href*="#"]')`, just pass the target `new SmoothScroll('#mytarget')` and let the coder call it from whatever events he wants to, not necessarily anchor events, not once per object but perhaps with delegation, and managing interaction in whatever way he needs to.

All the hash (#) utilities you did are interesting, but often they're already managed by the coder on a broader context, and after all, they're not related to 'smooth scrolling' at all. They're just application state, with a lot more implications than just marking the scroll position.

Anyway, instead of throwing away part of your work, you could just add the possibilty. After all, distinguishing anchors selectors from other type of selectors, it's quite simple. So, on the constructor, you could check for anchor/not anchor selector, then behave differently. If anchor, do as current. If not, bypass all events and actions and just scroll to the target. 

Regards
