### ISSUE TITLE
Support for standard querySelector syntax

### ISSUE THREAD

**Issue by ondrejsevcik** [cferdinandi/smooth-scroll#302]
Hi, it would be great if smooth-scroll would support standard querySelector syntax. 

I want to use it for all links starting with a hash `a[href^="#"]` but then I found out that this plugin has it's own syntax for querying DOM elements. 

What do you think?

**Comment by cferdinandi** [comment]
This *would* be a great feature, but it's impractical to implement the way the plugin is written.

Rather than adding an event listener for every link, Smooth Scroll takes advantage of event bubbling. It listens for all clicks, and then checks to see if the clicked element has the class, data attribute, etc. passed in for smooth scroll links.

This is better for performance, but there's no good way to use a traditional `querySelector` selector against it.

**Comment by ondrejsevcik** [comment]
Fair enough 👍

**Comment by cferdinandi** [comment]
If you know of a way I'm missing, though, I'm all ears. I would truly love to add this in. I think it would make the plugin a lot stronger.

**Comment by ondrejsevcik** [comment]
The simplest solution is probably to simply grab all items in the DOM and check whether the target is included. 

http://codepen.io/ondrejsevcik/pen/rWvbxR?editors=1010

I don't know about the performance, but how often users clicks on a link... 🤔

**Comment by cferdinandi** [comment]
Hmm... let me explore this a bit more.

**Comment by cferdinandi** [comment]
Hey there. This should be fixed with v10.2.0, merging shortly.

https://github.com/cferdinandi/smooth-scroll/pull/303

**Comment by ondrejsevcik** [comment]
Wohooo 😊  awesome 👍
