### ISSUE TITLE
Smooth Scroll to top doesn't work

### ISSUE THREAD

**Issue by hackuun** [cferdinandi/smooth-scroll#394]
For some reason, smooth scroll doesn't work with this setup:

```html
<div class="smooth-wrapper">
    <nav id="top">
      <a data-scroll href="#bazinga">Anchor Link</a>
      <a data-scroll href="#bazinga">Anchor Link 2</a>
    </nav>

    <div id="bazinga">
      <a data-scroll href="#top">Top</a>
    </div>
  </div>
```

```
.smooth-wrapper {
  position: relative;
  width: 100%;
  height: 2000px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
nav {
  position: absolute;
  top: 0;
  left: 0;
}

#bazinga {
  width: 200px;
  height: 200px;
  background-color: red;
}
```

```js
let scroll = new SmoothScroll('a[href*="#"]')
```

**Comment by cferdinandi** [comment]
Previously unidentified browser quirk. Some browsers treat `#top` as a known point and automatically jump you to the top of the page. This behavior is overriding Smooth Scroll, so when it runs, the starting position is `0` instead of some ways down the page.

Give that `nav` literally any other ID and it will work as expected. I'll update the docs to reflect this.

**Comment by cferdinandi** [comment]
This will be fixed and fully function in v14.x, currently in development and pending testing.
