### ISSUE TITLE
Error and instant jump when going backwards in browser history to state with no hash

### ISSUE THREAD

**Issue by dk1m** [cferdinandi/smooth-scroll#441]
This can be reproduced on the demo page, so hopefully my lack of a reduced test case is acceptable.

Environment:
macOS 10.13.4 
Chrome 67.0.3396.87
Firefox 60.0.2
Smooth Scroll 14.2.0

Repro steps:
1. Load demo page
2. Click any link to scroll down
3. Go back using the browser back button

Expected results:
No error and a smooth scroll to the top of the page.

Actual results:
Error and an instant jump to the top of the page. In Chrome, `Uncaught TypeError: Cannot read property 'smoothScroll' of null`. In Firefox, `TypeError: history.state is null`.

**Comment by cferdinandi** [comment]
I'm not running the proper checks to prevent that error from appearing, so that's a must-fix.

The behavior, though, I'm less clear on. the `history.state` isn't set until an initial click happens, so on a back-click to the starting point, there's no historical location to jump to.

I *could* set a state with the current window location as the default when the script is instantiated, *but*... I'm not actually sure that's the right call. It could have unintended interactions with other scripts and what not.

In writing this, I think there may be another alternative:
- On instantiation, do nothing different.
- When the user clicks a smooth scrolling link, if there's no `history.state` currently set, create one using the current location, then scroll and update the `history.state` as you normally would.

This gives the script a default location to hook into, but *only* after the DOM has been interacted with.

Thoughts?

**Comment by dk1m** [comment]
That sounds reasonable. You would basically go back to where you left off when you clicked the first link, correct? I actually think that's a better solution than just going back to the position when the script is instantiated. From my limited knowledge on this subject, it seems the browser would do the same thing and take you back to the scroll position that you were at when you clicked the link.

**Comment by cferdinandi** [comment]
Cool, and yea that's how the browser would do it, too.

No estimated time to implement this, but this is relatively straightforward. I'll prioritize.

**Comment by dk1m** [comment]
Great. Thanks a lot, @cferdinandi! I appreciate the quick response, and I appreciate the great work you put into this lib.

**Comment by nicolay-zlobin** [comment]
Hello, I'm using cferdinandi/tabby library and smooth-scroll simultaneously. When I switch tabs I see an error: `Uncaught TypeError: Cannot read property 'smoothScroll' of null` that can be related to this issue somehow.
<img width="878" alt="screen shot 2018-06-26 at 18 55 14" src="https://user-images.githubusercontent.com/25667028/41924376-86a2a97a-7972-11e8-89f0-fca60d3dde04.png">

**Comment by cferdinandi** [comment]
related: https://github.com/cferdinandi/smooth-scroll/pull/443

**Comment by blahed** [comment]
Any updates on this one?

**Comment by cferdinandi** [comment]
Thanks for you patience, everyone! Just pushed v15.0.1, which fixes this issue.
