### ISSUE TITLE
[feature] Mutation Observer on header element

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#453]
It would be cool if `smooth-scroll` could use a [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) on the `header` element so it can adjust the scroll offset when that header element changes (which can quite often happen by media queries).

**Comment by cferdinandi** [comment]
This is a cool idea. I think at the very least, I should calculate the header height in real time as I'm about to scroll instead of caching that when the script is initiated.

`MutationObserver` adds a bit more weight, doesn't have the deep backwards compatibility the script currently enjoys, and doesn't have a great polyfill option.

**Comment by cferdinandi** [comment]
Alright, updated: https://github.com/cferdinandi/smooth-scroll/releases/tag/v15.1.0

**Comment by cferdinandi** [comment]
(I understand this isn't exactly what you asked for, but I hope it gets you 99% there with better performance and easier script maintenance).

**Comment by strarsis** [comment]
@cferdinandi: A MutationObserver would make more sense with your other project [gumshoe](https://github.com/cferdinandi/gumshoe) (which I also heavily use), because updating the dimensions (of `selectorHeader`) during scrolling or using polling would be too performance consuming.
