### ISSUE TITLE
Sticky header not working correctly

### ISSUE THREAD

**Issue by Flyrell** [cferdinandi/smooth-scroll#480]
Hi,
thanks for the good work. I actually wanted to use the library for one of my new websites which has the sticky header and it seems like it's not working properly. After navigating back and forth with the different links it ends on the weird offsets. Also, the anchor navigates to the top sometimes even though the id it's pointing to is somewhere else.

I tried to fix it, but couldn't figure out what's going on while travelling.  I somehow managed to fix it accidentally by commenting the `header.offsetTop` in `getHeight` function, but tbh I have no idea why this works.

I was counting maybe someone has the same issue or at least has the idea why this is happening. So far I tested only in Chrome (75.0.3770.100) on macOS and Chrome for Android (75.0.3770.101).

The issue can be found in the demo here: https://civicko.zbinski.dev/

My configuration: 
```javascript
new SmoothScroll('a[data-scroll]', {
    speed: 500,
    clip: true,
    speedAsDuration: true,
    easing: 'easeInOutQuint',
    header: '[data-scroll-header]'
});
```

**Comment by cferdinandi** [comment]
Hi there,

I unfortunately am not able to debug individual implementation issues, *but...*

In my experience dealing with stuff like this in the past, 99.9% of these kinds of offset issues are caused by CSS and how positioning can affect the internal offset calculations.

I did notice you're using `position: sticky`. I believe that's what's causing the issue: https://github.com/cferdinandi/smooth-scroll/issues/463#issuecomment-473376884

More details on how to deal with this at the link above.
