### ISSUE TITLE
`window` is not defined on server-side rendering

### ISSUE THREAD

**Issue by renanbatel** [cferdinandi/smooth-scroll#481]
The latest versions aren't working on server side rendering because `window` doesn't exist, version 14.0.0 works fine.

To reproduce it just import the lib in any javascript server-side rendered app. Example: https://codesandbox.io/s/nextjs-blog-post-example-fhzn4

**Comment by grgr-dkrk** [comment]
Since version 14.2.1, the entry point has been changed from `./dist/smooth-scroll.min.js` to `./dist/smooth-scroll.polyfills.min.js`.

https://github.com/cferdinandi/smooth-scroll/commit/b89161c9c8cb05cb2d01985a78cd4fccab35578f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L5-R5

These polyfills contained in its refer to the `window` object at initialization, which causes an error on the server-side.

https://github.com/cferdinandi/smooth-scroll/blob/31e7bc7bba8fbc145676fe07877de8ef84449b91/dist/smooth-scroll.polyfills.js#L13

https://github.com/cferdinandi/smooth-scroll/blob/31e7bc7bba8fbc145676fe07877de8ef84449b91/dist/smooth-scroll.polyfills.js#L32

https://github.com/cferdinandi/smooth-scroll/blob/31e7bc7bba8fbc145676fe07877de8ef84449b91/dist/smooth-scroll.polyfills.js#L55

So I think should change these polyfills to check  `typeof window`, and set it to avoid the process when` window` object is undefined.
I [applied](https://github.com/grgr-dkrk/smooth-scroll/blob/forssr/dist/smooth-scroll.polyfills.min.js) these polyfills, and It seems to be fine on Next.js and Gatsby.

We can also import a module that does not contain polyfills if it does not support legacy browsers.
`import SmoothScroll from 'smooth-scroll/dist/smooth-scroll'`.

**Comment by cferdinandi** [comment]
Should I update the default to NOT be the polyfilled version?

**Comment by cferdinandi** [comment]
Any thoughts on the above?

**Comment by cferdinandi** [comment]
closed due to nonresponse

**Comment by jmp1548** [comment]
having the same issue
