### ISSUE TITLE
Manual update: Scrolling to an anchor link on another page

### ISSUE THREAD

**Issue by a4bits** [cferdinandi/smooth-scroll#491]
There is one nice trick,
you can use #to-section in URL and on html side use id="section"

when you load document you could use thing like
```
if (window.location.hash.substr(1) === 'to-section')
        scroll.animateScroll(document.querySelector('#section'));
```

and it should scroll nicely to

`<section id="section">`

**Comment by cferdinandi** [comment]
it causes a jump. By the time the JS executes, the browser has typically already jumped down to the anchor.

**Comment by a4bits** [comment]
but... if you do not have any <section id="to-section"> defined it does not know where to jump :-) the idea is to use <section id="section"> in html and in url to use #to-section

**Comment by cferdinandi** [comment]
Ohhh I see what you're doing! That's clever! I'll update the docs accordingly!

I missed the `to-` prefix at the beginning.

**Comment by a4bits** [comment]
I'm happy to help :-)

**Comment by ionurboz** [comment]
```
var scroll = new SmoothScroll();
window.onload = function()
{
  var hashTo = window.location.hash.substring(1);

  if(hashTo.indexOf("to--") > -1)
  {
    var hash = hashTo.substring(hashTo.indexOf("to--")+1);
  }
  else
    hash = hashTo;

  scroll.animateScroll(
    document.querySelector('#'+hash),
  );
};
```
this works very well for me...

`#to--example` -> Since it cannot find it on the page, it accepts the starting point as zero and applies the animation.

`#example` -> The page automatically goes to the region defined as "example". It then aligns itself with the animation, if any, to the value (Offset).

Both work properly. Which one is up to you. The first option may be negative for SEO, since you link a non-selective. The second option may not be as desired / visually in terms of user experience. As a result, the page jumps directly to the element and then animates. Of course, this situation is not visible. However, we, the developers, take into account even the smallest details: D

**Comment by cferdinandi** [comment]
Hi all, I'm deprecating this plugin and recommending everyone switch over to a now well supported CSS-native approach: https://gomakethings.com/how-to-animate-scrolling-to-anchor-links-with-one-line-of-css/

The above technique supports this use-case out-of-the-box, without hacking in any solutions.
