### ISSUE TITLE
Offsetting for fixed header when coming from another page.

### ISSUE THREAD

**Issue by moxdev** [cferdinandi/smooth-scroll#498]
Is there a way to offset the height when using a fixed header and coming in from another page? 

I have a front page with several scrollable sections (ie. #services) and a separate blog page. Using `header: '[data-scroll-header]'` works great on the front page but when I return to the front page from the blog page it no longer offsets the header. Kind of new to javascript so any advice would be greatly appreciated! Awesome work btw!

**Comment by cferdinandi** [comment]
Smooth Scroll doesn't support scrolling to anchor links when coming from another page, but... the workaround suggested here might be of help: https://github.com/cferdinandi/smooth-scroll/issues/491

**Comment by ionurboz** [comment]
```
var scroll = new SmoothScroll();
window.onload = function()
{
  var hashTo = window.location.hash.substring(1);

  if(hashTo.indexOf("to--") > -1)
  {
    var hash = hashTo.substring(hashTo.indexOf("to--")+1);
  }
  else
    hash = hashTo;

  scroll.animateScroll(
    document.querySelector('#'+hash),
  );
};
```
this works very well for me...

`#to--example` -> Since it cannot find it on the page, it accepts the starting point as zero and applies the animation.

`#example` -> The page automatically goes to the region defined as "example". It then aligns itself with the animation, if any, to the value (Offset).

Both work properly. Which one is up to you. The first option may be negative for SEO, since you link a non-selective. The second option may not be as desired / visually in terms of user experience. As a result, the page jumps directly to the element and then animates. Of course, this situation is not visible. However, we, the developers, take into account even the smallest details: D
