### ISSUE TITLE
Polyfill for scroll-behavior?

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/smooth-scroll#499]
Not sure whether this has been asked here, 
but could `smooth-scroll` be used as a polyfill for [`scroll-behavior`](https://developer.mozilla.org/de/docs/Web/CSS/scroll-behavior)?

`scroll-behavior` can be set for scrolling boxes (and for body or for everything) to e.g. `smooth`.
The advantages are that this would be implemented natively by supporting browsers and 
that the end user can still override this behaviour.

**Comment by cferdinandi** [comment]
I don't think so. Smooth Scroll does a _lot_ more, and with different conventions. I think a dedicated polyfill ([like this one](https://github.com/iamdustan/smoothscroll)) is a better choice.

I tend to use `scroll-behavior` instead of this plugin nearly 100% of the time now, and am totally cool with the idea that smooth scrolling is a progressive enhancement that only supporting browsers get.

**Comment by strarsis** [comment]
@cferdinandi: The polyfill has many open issues and the last commit was months ago, 
hence I thought about making `smooth-scroll` use a part of its code for polyfilling.
