### ISSUE TITLE
Setting up auto offset

### ISSUE THREAD

**Issue by ArtemisGraphic** [cferdinandi/smooth-scroll#503]
I'm trying to implement smooth-scroll with auto offste but it seems I can't make it work.

documentation says that this must be added on bottom of the page `var scroll = new SmoothScroll('a[href*="#"]');`

I have a sticky navbar and documentation says to add:

```
<script>
	var scroll = new SmoothScroll('.some-selector',{
		header: '[data-scroll-header]'
	});
</script>
```

My navbar looks like this `<div data-scroll-header class="navbar sticky-top justify-content-between">`

I tried different solutions but I can't get it to work:

` var scroll = new SmoothScroll('a[href*="#"]', {header: '[data-scroll-header]'} );` makes the scroll go crazy, sometimes goes on the navbar, sometimes on the href. Other stays stuck on the top of the page.

`var scroll = new SmoothScroll('navbar', {header: '[data-scroll-header]'} );` This does not initialize Smooth Scroll.

Every other solution I tried does not use offset.

**Comment by cferdinandi** [comment]
Reduced test case please.

**Comment by FilippoSalvarani** [comment]
https://codepen.io/artemisgraphic21/pen/OJPrepV

**Comment by FilippoSalvarani** [comment]
> Offset is working exactly as I would expect it to. One thing you may need to do in your CSS is add some padding to the `body` so that your first item isn't hidden, but otherwise, this is working perfectly.

It works, but if you click on the same link more than once you will see the scroll goes up and down, from the navbar to the anchor tag.

**Comment by cferdinandi** [comment]
Ah, thanks for clarifying! Reopened.

**Comment by FilippoSalvarani** [comment]
Any suggestion? I'm trying but it looks like a bug to me...

**Comment by ionurboz** [comment]
```
var scroll = new SmoothScroll();
window.onload = function()
{
  var hashTo = window.location.hash.substring(1);

  if(hashTo.indexOf("to--") > -1)
  {
    var hash = hashTo.substring(hashTo.indexOf("to--")+1);
  }
  else
    hash = hashTo;

  scroll.animateScroll(
    document.querySelector('#'+hash),
  );
};
```
this works very well for me...

`#to--example` -> Since it cannot find it on the page, it accepts the starting point as zero and applies the animation.

`#example` -> The page automatically goes to the region defined as "example". It then aligns itself with the animation, if any, to the value (Offset).

Both work properly. Which one is up to you. The first option may be negative for SEO, since you link a non-selective. The second option may not be as desired / visually in terms of user experience. As a result, the page jumps directly to the element and then animates. Of course, this situation is not visible. However, we, the developers, take into account even the smallest details: D

**Comment by Antimated** [comment]
Seems like "position: sticky" is the issue (at least in my case). For now I just set a hardcoded offset.

**Comment by cferdinandi** [comment]
Hi there, I'm deprecating this plugin and recommending everyone switch over to a now well supported CSS-native approach: https://gomakethings.com/how-to-animate-scrolling-to-anchor-links-with-one-line-of-css/

It supports `position: sticky`, and you can also [prevent your anchor links from scrolling behind the header](https://gomakethings.com/how-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header-with-one-line-of-css/).
